version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
      TZ: Tokyo
    ports:
      - "4306:3306"  #Sequel ProでDBを確認する為、4306としておく
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d
      # - mysql-data:/var/lib/mysql
    env_file: db.env
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/giver
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    env_file: db.env
volumes:
  mysql-data: